#ifndef IntDoubleVectorPair_CC
#define IntDoubleVectorPair_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "IntDoubleVectorPair.h"

GET_V_TABLE(IntDoubleVectorPair)

#endif