#ifndef KMEANS_NORM_VECTOR_MAP_CC
#define KMEANS_NORM_VECTOR_MAP_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "KMeansNormVectorMap.h"

GET_V_TABLE(KMeansNormVectorMap)

#endif
