#ifndef KMeansSampleSelection_CC
#define KMeansSampleSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "KMeansSampleSelection.h"

GET_V_TABLE(KMeansSampleSelection)

#endif