#ifndef LDADocIDAggregate_CC
#define LDADocIDAggregate_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDADocIDAggregate.h"

GET_V_TABLE(LDADocIDAggregate)

#endif
