#ifndef LDAInitialTopicProbSelection_CC
#define LDAInitialTopicProbSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDAInitialTopicProbSelection.h"

GET_V_TABLE(LDAInitialTopicProbSelection)

#endif
