#ifndef ScanIntDoubleVectorPairSet_CC
#define ScanIntDoubleVectorPairSet_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "ScanIntDoubleVectorPairSet.h"

GET_V_TABLE(ScanIntDoubleVectorPairSet)

#endif
