#ifndef ScanLDADocumentSet_CC
#define ScanLDADocumentSet_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "ScanLDADocumentSet.h"

GET_V_TABLE(ScanLDADocumentSet)

#endif