#ifndef WriteIntDoubleVectorPairSet_CC
#define WriteIntDoubleVectorPairSet_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "WriteIntDoubleVectorPairSet.h"

GET_V_TABLE(WriteIntDoubleVectorPairSet)

#endif