
#ifndef PDBCATALOG_VTABLEMAP_CONST_C_
#define PDBCATALOG_VTABLEMAP_CONST_C_

/*
 * VTableMap.cc
 *
 *  Created on: Dec 11, 2015
 *      Author: carlos
 */

// This header is auto-generated by SConstruct... it includes all of the header files
// in BuiltInPDBObjects/headers
#include "BuiltinPDBObjects.h"
#include "PDBDebug.h"
#include "UseTemporaryAllocationBlock.h"
#include "VTableMap.cc"

#include <dlfcn.h>
#include <unistd.h>
#include <cctype>
#include <iostream>

namespace pdb {

VTableMap::VTableMap() {
    logger = std::make_shared<PDBLogger>("vtablemap.log");
    catalog = nullptr;
    stringstream ss;
    ss << &(myLock);
    PDB_COUT << "to initialize lock at " << ss.str() << std::endl;
    pthread_mutex_init(&(myLock), nullptr);
    pthread_mutex_init(&(myOtherLock), nullptr);
    for (unsigned int i = 0; i < 16384; i++) {
        allVTables.push_back(nullptr);
    }
#ifdef DEBUG_VTABLE_FIXING
    numFixes = 0;
#endif
// this will add a type identifier for each one of the built-in types
// (building the map from type name to ID) and then after that, it
// is going to create an instance of each of the types, and extract
// the v-table pointer from it, adding that to the allVTables vector
#include "BuiltinPDBObjects.cc"
}

// the global variables all live here!!
#include "GlobalVariables.cc"
} /* namespace pdb */


#endif
