#ifndef EMBEDDING_SEGMENT_CC
#define EMBEDDING_SEGMENT_CC

// This program is generated by machine at a random time

#include "EmbeddingSegment.h"
#include "GetVTable.h"

GET_V_TABLE(EmbeddingSegment)


#endif
