#ifndef EMBEDDING_LOOKUP_SPARSE_CC
#define EMBEDDING_LOOKUP_SPARSE_CC

// This program is generated by machine at a random time

#include "EmbeddingLookupSparse.h"
#include "GetVTable.h"

GET_V_TABLE(EmbeddingLookupSparse)


#endif
