#ifndef SEMANTIC_CLASSIFIER_SINGLEBLOCK_CC
#define SEMANTIC_CLASSIFIER_SINGLEBLOCK_CC

// This program is generated by machine at a random time

#include "SemanticClassifierSingleBlock.h"
#include "GetVTable.h"

GET_V_TABLE(SemanticClassifierSingleBlock)

float sigmoid(float x) { return 1 / (1 + exp(-x)); }

float relu(float x) { return std::max(0.0, x); }

float outLabel(float x) {
    float threshold = 0.5;
    if (x > threshold) {
        return 1;
    } else {
        return 0;
    }
}

#endif
