#ifndef SEMANTIC_CLASSIFIER_CC
#define SEMANTIC_CLASSIFIER_CC

// This program is generated by machine at a random time

#include "SemanticClassifier.h"
#include "GetVTable.h"

GET_V_TABLE(SemanticClassifier)

#endif
