#ifndef SEMANTIC_CLASSIFIER_SINGLEBLOCK_CC
#define SEMANTIC_CLASSIFIER_SINGLEBLOCK_CC

// This program is generated by machine at a random time

#include "SemanticClassifierSingleBlock.h"
#include "GetVTable.h"

GET_V_TABLE(SemanticClassifierSingleBlock)

double sigmoid(double x) { return 1 / (1 + exp(-x)); }

double relu(double x) { return std::max(0.0, x); }

double outLabel(double x) {
    double threshold = 0.5;
    if (x > threshold) {
        return 1;
    } else {
        return 0;
    }
}

#endif
