#ifndef PDB_QUERYINTERMEDIARYREPTESTS_QUERYINTERMEDIARYREPTESTSRUNNER_H
#define PDB_QUERYINTERMEDIARYREPTESTS_QUERYINTERMEDIARYREPTESTSRUNNER_H

#include "qunit.h"

using QUnit::UnitTest;

namespace pdb_tests {
void runQueryIrTests(UnitTest& qunit);
}

#endif  // PDB_QUERYINTERMEDIARYREPTESTS_QUERYINTERMEDIARYREPTESTSRUNNER_H
