#ifndef LDADocWordTopicJoin_CC
#define LDADocWordTopicJoin_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocWordTopicJoin.h"

GET_V_TABLE(LDADocWordTopicJoin)

#endif
