#ifndef LDADocTopicAggregate_CC
#define LDADocTopicAggregate_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocTopicAggregate.h"

GET_V_TABLE(LDADocTopicAggregate)

#endif
