#ifndef LDA_DOC_WORD_TOPIC_IDENTITY_CC
#define LDA_DOC_WORD_TOPIC_IDENTITY_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocWordTopicAssignmentIdentity.h"

GET_V_TABLE(LDADocWordTopicAssignmentIdentity)

#endif
