#ifndef LDADocTopicFromCountAggregate_CC
#define LDADocTopicFromCountAggregate_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocTopicFromCountAggregate.h"

GET_V_TABLE(LDADocTopicFromCountAggregate)

#endif