#ifndef LDADocTopicProbSelection_CC
#define LDADocTopicProbSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocTopicProbSelection.h"

GET_V_TABLE(LDADocTopicProbSelection)

#endif