#ifndef LDADocWordTopicCount_CC
#define LDADocWordTopicCount_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDADocWordTopicCount.h"

GET_V_TABLE(LDADocWordTopicCount)

#endif