#ifndef LDAInitialWordTopicProbSelection_CC
#define LDAInitialWordTopicProbSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDAInitialWordTopicProbSelection.h"

GET_V_TABLE(LDAInitialWordTopicProbSelection)

#endif
