#ifndef LDAInitialWordTopicProbMultiSelection_CC
#define LDAInitialWordTopicProbMultiSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDAInitialWordTopicProbMultiSelection.h"

GET_V_TABLE(LDAInitialWordTopicProbMultiSelection)

#endif
