#ifndef LDATopicWordAggregate_CC
#define LDATopicWordAggregate_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDATopicWordAggregate.h"

GET_V_TABLE(LDATopicWordAggregate)

#endif