#ifndef LDATopicWordProbMultiSelection_CC
#define LDATopicWordProbMultiSelection_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDATopicWordProbMultiSelection.h"

GET_V_TABLE(LDATopicWordProbMultiSelection)

#endif