#ifndef LDATopicWordProb_CC
#define LDATopicWordProb_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDATopicWordProb.h"

GET_V_TABLE(LDATopicWordProb)

#endif