#ifndef LDAWordTopicAggregate_CC
#define LDAWordTopicAggregate_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/LDAWordTopicAggregate.h"

GET_V_TABLE(LDAWordTopicAggregate)

#endif