#ifndef SCAN_TOPICS_PER_WORD_CC
#define SCAN_TOPICS_PER_WORD_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/ScanTopicsPerWord.h"

GET_V_TABLE(ScanTopicsPerWord)

#endif
