#ifndef WRITE_TOPIC_PER_WORD_CC
#define WRITE_TOPIC_PER_WORD_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/WriteTopicsPerWord.h"

GET_V_TABLE(WriteTopicsPerWord)

#endif
