#ifndef WRITE_DOC_WORD_TOPIC_CC
#define WRITE_DOC_WORD_TOPIC_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/WriteLDADocWordTopicAssignment.h"

GET_V_TABLE(WriteLDADocWordTopicAssignment)

#endif
