#ifndef WriteLDADocWordTopicAssignmentSet_CC
#define WriteLDADocWordTopicAssignmentSet_CC

// This program is generated by machine at a random time

#include "GetVTable.h"
#include "LDA/WriteLDADocWordTopicAssignmentSet.h"

GET_V_TABLE(WriteLDADocWordTopicAssignmentSet)

#endif